version: '3.8'

services:
  api_a:
    build:
      context: ./api_a
      dockerfile: Dockerfile
    container_name: api_a
    ports:
      - "5000:5000"
    networks:
      - api_network
    depends_on:
      - api_b
    environment:
      - FLASK_ENV=development

  api_b:
    build:
      context: ./api_b
      dockerfile: Dockerfile
    container_name: api_b
    ports:
      - "5001:5001"
    networks:
      - api_network
    environment:
      - FLASK_ENV=development

networks:
  api_network:
    driver: bridge
